version: "2"
services:
  database:
    image: postgres:9.6.14
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 123
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - 5432

  server:
    build: .
    environment:
      # Rails Settings
      DATABASE_URL:
      SECRET_KEY_BASE:

      # AWS Settings
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      BUCKET_NAME:

      # Mailgun Settings
      MAILGUN_API_KEY:
      MAILGUN_DOMAIN:
      REDEFINE_PASSWORD_URL:
    links:
      - database
    ports:
      - '80:3000'
    volumes:
      - .:/home/app

volumes:
  database:
    driver: local
