# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ae459145c62c98e9bd206ce7f1b42a632ee0b204a2e6f5933ecb26baeb954218d1fb6ffe882444303e9933defc580b5dfcf4cca8f8b62cd9346510a9675530

test:
  secret_key_base: 24116d4b9fb6d23e6816369e7649c9b8a4ed8af0312bf2f2436ab0c9c4629449465b6eb56dbfa106726abedb58971a71fee10808fc5edf023b79070f37376407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
